### ISSUE TITLE
Setting the magmom rather than use saxis and possibility for more than 2 elements are included?

### ISSUE THREAD

**Issue by rottenapple11** [maituoy/BayesianOpt4dftu#14]
Question 1:
May I know how to set the magmom from input.json?
In ASE,  it is like this:

from ase import Atoms, Atom
from ase.calculators.vasp import Vasp

a = [6.5, 6.5, 7.7]
d = 2.3608
NaCl = Atoms([Atom('Na', [0, 0, 0], magmom=1.928),
              Atom('Cl', [0, 0, d], magmom=0.75)],
             cell=a)

calc = Vasp(prec='Accurate',
            xc='PBE',
            lreal=False)
NaCl.calc = calc

print(NaCl.get_magnetic_moment())

https://wiki.fysik.dtu.dk/ase/ase/calculators/vasp.html

Sorry but I'm pretty new to ASE and not sure how to add the magmom in the input.json, since the format is different from the ASE manual and the input.json. General flags does not recognize magmom too. If left all empty, vasp compiled by default cannot run spin-orbit interactions tasks.

Any suggestion? Not to recompile vasp, if possible.

Question 2:
I have a system let's say MnCO3. It is possible to train the U parameter for Mn, O in theory without modifying the result, correct? Haven't tested that because I got stuck in the first question.

Thanks in advance.

**Comment by maituoy** [comment]
Hi,

1. For your first question, there are two elements for each atom in the input.json, the first one sets the atomic position of the atom while the second element set the MAGMOM. For calculations with the spin-orbit coupling, the magmom will be a 1d array indicating the initial magmom along each spin axis. While for calculations without spin-orbit coupling, it can be a single value. To avoid mathematical error, the magmom has to be set to an infinitesimal value instead of 0 if it has no magnetic moment.
2. I don't quite understand what you mean by training the Mn, O without modifying the result. If you are talking about optimizing the U for two elements simultaneously, the answer is yes. You can check the 2d example in the example folder.

**Comment by maituoy** [comment]
"atoms": [
        [
            "Mn",
            [
                0,
                0,
                0
            ],
            1e-06
         ],  

This is an example of an Mn atom at (0,0,0) coordinate with an initial magnetic moment of 0 without spin-orbital coupling.

**Comment by rottenapple11** [comment]
> ```
> "atoms": [
>     [
>         "Mn",
>         [
>             0,
>             0,
>             0
>         ],
>         1e-06
>      ],  
> ```
> 
> This is an example of an Mn atom at (0,0,0) coordinate with an initial magnetic moment of 0 without spin-orbital coupling.

Thank you very much.
