### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zc994646659** [maituoy/BayesianOpt4dftu#9]
Mr Yu,Thank you for your advice .
1.the band structures of HSE and DFT+U are very similar.it is not neccessary plus U? why? Doesn’t it mean that the U value is correct?How to choose the initial Ueff? Linear response result?
2.Is there any other adjustable parameters in the example.py, or it need to be modified?and hot to change the U range? which parameter？ 。。。
zhouchao

**Comment by zc994646659** [comment]
There are some problems when I execute the program,could you give me some advice?
[input.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7371266/input.txt
[example.txt](https://github.com/maituoy/BayesianOpt4dftu/files/7371269/example.txt)
![QQ截图20211019154519](https://user-images.githubusercontent.com/76720982/137866167-087a65f8-df8f-4e51-b344-c21c950b4fc6.png)
)

**Comment by maituoy** [comment]
1. I mean if the delta_band of PBE is small or the delta_band in the optimization process is always small, it might not be necessary to apply a U correction since you've already had good electronics structures with a low rank functional.
2. All the arguments are adjustable. Please read the example.py.
3. Error: Please update your BO package and see if it will be resolved. I'm not sure what version of BO you were using.

Best
